[[plugins]]
repo = 'jiangmiao/auto-pairs'

# unite
[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'
on_source = 'unite.vim'

# comment
[[plugins]]
repo = 'tomtom/tcomment_vim'

# ruby
[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

# markdown
[[plugins]]
repo = 'godlygeek/tabular'
on_ft = ['markdown', 'md']

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown', 'md']

# toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

