dist: trusty

addons:
    apt:
        packages:
        - git
        - build-essential
        - vim
        - curl
        - wget

before_script:
    - cat /etc/lsb-release | awk -F= '{if($1=="DISTRIB_CODENAME") print $2}'
    - vim --version
    - cd $HOME && git clone https://github.com/Tiryoh/dotfiles.git && cd dotfiles && git checkout -b dev/autobuild origin/dev/autobuild

script:
    - cd $HOME/dotfiles && /bin/bash -ec 'make vim-setup_for_docker; make bash'

